language: python
sudo: false

install:
  - pip install flake8
  - pip install pyinstaller

script:
  - pyinstaller -F -w painter.py

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: B5pDFv25m+rNfI3ETI0Re2MlWkQb30DaHGaYP2KFR9nxVTuNHslcoglzAo723ut7o4mNTOhXZiVfrnsvyGmFFWxxhp0lWhN3QlgIav3uwnxaTvoWFen7cEFXa+XlKMs8OY8n2JlzsQzENKaXsZ3enXThBVhUuMrCM/YAg6YpSKmGZmN1LSNxw+j9xovxjy2d0v8LzgNPJJMOjJRyO6OWnbO9rPZ+q/wa7PSKhhGu/bhjorTOuXCnuZh4zIutNJYC4nq55RrE11I/Uj0jqm0TnOFyYKV276NafhirkAIM5QaRyPjPlnB3SNnDEEraY7xqYAb4jMW8jMPK5+PSoyckhPxGvOLH+S7Xkq4w1xjKS2cS3bL6TgWh2qySoxQdiAew5+mtSv+FdOdqDBkbY17RaLX4hNAySrDOr5yEOcajdkdt5VOXXtv0w4efABgNT7Xsh7kmJDcYFD8gpMeuEQIw/XpMT+SUQlD+q5qmHVPNrpdqqWmBwm4FzWvcPGSExfXFJ4T83xCyr85E9DxOePLohiiZmNxmiOh4Jc68XPn73spNU1HCyPC1ZltaDVQZP7GinAmyS2ZgEp6iRNsSoLc8VkNqoF7IxggYHg/vt696ybyD4GENDYmnmyhp+CCmTUvQsLsUGkW/dK9Faa1WTGJZsMVWecIu5+sGnn9JdmmAXXc=
  file:
    # The names of the binaries to output
    - dist/painter.exe
  on:
    repo: Eskimon/draw-on-stream-telestrator
    tags: true
