language: python
sudo: false
install:
- pip install flake8
- pip install pyinstaller
script:
- pyinstaller -F -w painter.py
deploy:
  provider: releases
  file: dist/painter.exe
  api_key:
    secure: m12ZFZMy3tneNEBR/u3fZSj+A0gnGBEoKtViuGXstcwEZVq2HRsRpKK2NK+8UUzRBN8LHZNxpTa+qonCk8bY42nmSTzzlEmVvEX3pmSkRDFtX30m3rW8xWLUGnfKB8tINySl0cEa880w/4k9NwBblChJMtN6zpgUMc1eZNySJ9tH4ehofugHFweyByKrfHj8o0OKpkEOAsCvlem4EpYvj35gMewJKWzOzHeN8fFsVcN9YbS8pqwjbZqMqy0OyJWpnPBV5kdFvW7tYfcCuBPLFqL6rykPvovISu8OF0k9zHeMrqdeqwSuTQF31N9GVEYf9A75NatV634V44taRmIQccySxlZY+zgcR55Gg/YE1zoSaSjj/RtrUlUuyWquYHFAHOMPYtuC93F1Wb8mAia+dI98FUCm+J1xbo8sRi6Ue2e7+8p9jHqL06m0GFY/LGXeYGge2mYF0baWAbQ5EizN9IIbd0yMJVd+U+y3ye6FyxAeZ7EOthRO4OQmaEI6w3DkD3lT1HlD8ZFHR55mX/jiUH7KkAFNQhRUBsy36cF/CmH9nU+uH0ZyRFZTxjgGI+q13vQHzLL1qPwef46A8UXJHHQcyjShUj8nm5Npx/o9tfuEIBmTTmpkA45nO8R65on3of6bkKPZsGPHR9ANPu6cczuJ+lG3hsfYbtl9KVgzC6g=
  on:
    repo: Eskimon/draw-on-stream-telestrator
    branch: travis
