language: python
sudo: false
install:
- pip install flake8
- pip install pyinstaller
script:
- pyinstaller -F -w painter.py
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YSm6BHpKYeqog5S+EpsOoF+T23BlBhsj9KwnwiMQyqlDPhenmzzwYzbu9J1pun0oUaOq9xoyCs8EaEa4y959/IBDleWcnF5/eD8WNkpYSi+OBNwWjb42gqRl+KaD8uoAZcVSVOyv3fz0GLlsuE8+jVwf0avB297ML9VbgWpGm5wYN7p6BYZshwOPUAPomiUMT1hLuD3YV42HXpuZPz/fpKnOkhEFTCUGeDnJqS3DGHPOeXYP2w4WdUUuQHiqltqZsbTAO8r9E6Qb78XqH+7HuPB3UcDvMJthVVgSVQnojsbw0P/2PywSbZwviXYsybLlTMSV+4NPjwTYvnIfgzDpC3WgvZg+nbNLwzodVOmrA1C6c5Tl6k2mnbKIK1EpVQaVgIFq/XuMrwIvBziW0Hdn3w01j62lxu6Mlieb3V5goJTWntetN+px00JI/Wqwa8wKU3/fnM/kLsiuK2Tw9WW/RtFh84Bl6zd17pjhxX2h8RIweXI0+1xrEDrzmCt4IKdQHbyHL3eLkT9r0cA6hEkWdj7is8JGFFv8xzUbhmpFRGtU2s4CbOAsVp3dGzX38mV8I9kP5tMUIpnVkHmjzKUvNLUWitjaTgzZ/qmo+CqeUwuM6HUZYPl/60rDonh4iqaUeldfUbOk3r+AUVkBUzkxqxooaVF3E90wGyFGZ8PzFVE=
  file: dist/painter.exe
  on:
    repo: Eskimon/draw-on-stream-telestrator
    tags: true
