language: python
sudo: false

install:
  - pip install flake8
  - pip install pyinstaller

script:
  - pyinstaller -F -w painter.py

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bgd9bCIWFsIGzVoh1YbrB9Jits8wDXB8pxHc6izJ8VoTEHn88QiUTzUY5PuwJldt/h7k18yV9KreuTHvhkMnMIrvO8gHfjYPoXWLPvkhIhPGIxA2X3vfiQoHYaXTCbMYrv4mOTDiZOzxyR4HDUXzvU3O0jSFna4lA2lsRVrvVPwT8vwdCxpupYn180f5+8/hMm3WxbK2pmyCCI0tOoRJlZd6nAeXxSG0raOMoga0KZudhE/VY1lTIt7TeM+S9ZqeRJbQ8M81amQDIXq0zDjxHEak3wZ53d/Ufi8SOSQ7IiCkfjbL6N3cnXk4M0Y8yvQxh5vk5DpWlN0P3eqkZozhtd3ezJbAJaUR0ruqRjFIrXsysr4XeKk51sp1TZcQ7S9nTHrowR4Fm2a0E3cJsKTktzdBEeTkr2lpeoS7uMypT852snjSu35OGhFDmtArwUmJiwsOGAlmvX6C6b+Em8U3JOHkPJJ65M/pR6Kawxpm+m/NK7HqJCEpCqbauXeOWMfcg85Q1txUvu6a79Oy1pIfJ6RCg8xXXido//2V2hwSToF8QbHmCjDLaUOBb1DQFlpcKYQrpiAmpW+qbHxQAlh/ZdC19HV89eGEKsylYTtQwPZIJPqzmBwuXsbZ1/T1K0eKyE7JdXs3OYyI6SBywUNwSCLfqAYFExA7710jFy/+96Y=
  file:
    # The names of the binaries to output
    - dist/painter.exe
  on:
    repo: eskimon/draw-on-stream-telestrator
    tags: true
