branches:
  only:
  - master

build: off
test: off

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install pyinstaller"

test_script:
  - "echo test"
  
after_test:
  - "%PYTHON%/Scripts/pyinstaller.exe -w -F -n painter-%PYTHON_ARCH%bits.exe painter.py"
  
artifacts:
  - path: "dist/painter-%PYTHON_ARCH%bits.exe"
    name: painter
